new workflow: pkgdown

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -41,8 +41,7 @@ jobs:
           cache-version: 2
           extra-packages: |
             any::rcmdcheck
-            any
-            ::knitr
+            any::knitr
             any::rmarkdown,
             any::testthat
             any::sessioninfo
@@ -65,4 +64,31 @@ jobs:
           _R_CHECK_CRAN_INCOMING_: false
         run: |
           results = rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran", "--no-multiarch", "--no-examples"), error_on = "error", check_dir = "check")
+          if (results$status == 0) file.create("run_ok")
         shell: Rscript {0}
+
+      - name: Trigger doc workflow
+        if: github.event_name == 'pull_request'
+        run: |
+          touch run_ok
+          if [[ -f "run_ok" ]]; then
+            # Run curl -- https://stackoverflow.com/questions/38906626/curl-to-return-http-status-code-along-with-the-response
+            http_response=$(curl -s -o response.txt -w "%{http_code}"  \
+              -X POST \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization:token $GITHUB_PAT" \
+              https://api.github.com/repos/cgauvi/ben.R.utils/actions/workflows/41536288/dispatches \
+              -d '{"ref":"master"}'
+              )
+            # Inspect reponse
+            if [ $http_response != "204" ]; then
+                echo "Error with http response"
+                cat response.txt >&2
+                exit 1
+            fi
+            # Remove tmp file that exists
+            rm run_ok
+          else
+            printf '%s\n' "Couldnt manage to triger the documentation workflow" >&2
+            exit 1
+          fi
