added script to trigger doc automatically

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -69,18 +69,18 @@ jobs:
       - name: Trigger doc workflow
         if: github.event_name == 'pull_request'
         run: |
-            # Run curl -- https://stackoverflow.com/questions/38906626/curl-to-return-http-status-code-along-with-the-response
-            http_response=$(curl -s -o response.txt -w "%{http_code}"  \
+          # Run curl -- https://stackoverflow.com/questions/38906626/curl-to-return-http-status-code-along-with-the-response
+          http_response=$(curl -s -o response.txt -w "%{http_code}"  \
               -X POST \
               -H "Accept: application/vnd.github+json" \
               -H "Authorization:token $GITHUB_PAT" \
               https://api.github.com/repos/cgauvi/sfSpHelpers/actions/workflows/24790528/dispatches \
               -d '{"ref":"master"}'
               )
-            # Inspect reponse
-            if [ $http_response != "204" ]; then
-                echo "Error with http response"
-                cat response.txt >&2
-                exit 1
-            fi
+          # Inspect reponse
+          if [ $http_response != "204" ]; then
+              echo "Error with http response"
+              cat response.txt >&2
+              exit 1
+          fi
 
